### ISSUE TITLE
Tile center does not lie within a polygon sometimes

### ISSUE THREAD

**Issue by arunasank** [mapbox/mbtiles-extracts#12]
The `mbtiles-extracts` library checks to see if a tile center lies within a geojson polygon using the [`which-polygon`](https://github/com/mapbox/which-polygon) library.

However, there are times when the tile center does not lie within the geojson polygon, even though parts of the polygon are present in the tile as seen in the diagram below:

![](https://user-images.githubusercontent.com/3166852/48264399-61410300-e44f-11e8-8866-58b14f8c2989.png)

## Solution

Check if the tile bounding box intersects with the polygon to extract a tile as explained in https://github.com/mapbox/mbtiles-extracts/issues/10#issuecomment-437370452

cc/ @mourner @answerquest

**Comment by mourner** [comment]
Fixed by #14
