### ISSUE TITLE
Bounds and center aren't accurate

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/mbtiles-extracts#6]
The bounds and center metadata are currently inherited from the parent tiles, which leads to inaccurate default views for anything that uses those properties.

A new bounds and center for the extract, however rough, would be nice to have.

For example, a US extract created from a global tileset still retains the global bounds and center. Having me view somewhere near Turkey by default when I'm looking for the US.

**Comment by flowrean** [comment]
Why was this closed?
